# 1. ConfigMap for non-sensitive configuration.
# This tells the app how to find the database service.
apiVersion: v1
kind: ConfigMap
metadata:
  name: to-do-app-config
data:
  POSTGRES_HOST: "postgres-service"
---
# 2. Deployment for the main application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-deployment
  labels:
    app: to-do-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app-container
          image: akash210994/to-do-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: to-do-app-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"