# This file defines the Kubernetes objects for the Node.js notes application.

# 1. ConfigMap for non-sensitive configuration.
# This tells the app how to find the database service.
apiVersion: v1
kind: ConfigMap
metadata:
  name: to-do-app-config
data:
  POSTGRES_HOST: "postgres-service"
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-deployment
  labels:
    app: to-do-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app-container
          image: akash210994/to-do-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: to-do-app-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
# 3. Service to expose the notes application to the internet.
# Using type LoadBalancer will provision an external IP address on most cloud providers.
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80 # External port
      targetPort: 3000 # Internal port of the container
  selector:
    app: to-do-app

